version: "3"
services:
  mysql:
    ports:
      - ${MYSQL_PORTS}
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "clippers"
      MYSQL_ROOT_PASSWORD: ${PRISMA_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORTS} # This needs to cover the SRH_CONNECTION_STRING below (:6379)
  serverless-redis-http:
    ports:
      - "8079:80" # env.REDIS_URL needs to match this port
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${REDIS_SECRET}
      SRH_CONNECTION_STRING: "redis://redis:6379" # Using `redis` hostname since they're in the same Docker network.
volumes:
  mysql:
  redis-data:
