version: "3"
services:
  mysql:
    ports:
      - ${MYSQL_PORTS}
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "clippers"
      MYSQL_ROOT_PASSWORD: ${PRISMA_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORTS}
volumes:
  mysql:
  redis-data:
